spring:
  application:
    name: notification-service

  server:
    port: 8089

  mail:
    host: smtp.gmail.com
    port: 587
    username: fortestapp00000001@gmail.com
    password: "testtest00000001"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

kafka:
  bootstrap-servers: kafka:9092
  topics:
    test-topic: topicForNotification
  group-id: notification-group
  auto-offset-reset: earliest

logging:
  level:
    root: INFO
    com.example.business: DEBUG
    com.example.web: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB